[package]
name = "task-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
clearscreen = "3.0.0"
colored = "2.1.0"
crossterm = "0.28.1"
machine-info = "1.0.9"
regex = "1.10.6"
sysinfo = "0.31.4"
terminal_size = "0.3.0"
